name: attack4defense
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9.1
  - tqdm=4.54.1
  - torchvision=0.15.2
  - torchaudio=2.0.2
  - torch=2.0.1
  - timm=1.0.9
  - scipy=1.11.4
  - scikit-learn=1.4.2
  - scikit-image=0.22.0
  - requests=2.32.3
  - pytorch-lightning=1.5.0
  - pyspng=0.1.2
  - psutil=5.9.8
  - opencv-python=4.9.0.80
  - numpy=1.26.4
  - ninja=1.11.1.1
  - matplotlib=3.8.3
  - imageio-ffmpeg=0.4.3
  - future=1.0.0
  - easydict=1.13
  - click=8.0.0
  - webdataset=0.2.86
  - pyyaml=6.0.1
  - pandas=2.2.2
  - packaging=24.0
  - kornia=0.5.0
  - joblib=1.4.2
  - hydra-core=1.3.2
  - albumentations=0.5.2
